[package]
name = "daisy"
version = "0.1.0" # hack/release.sh
authors = [ "Petr Horáček <hrck@protonmail.com>" ]
edition = "2018"
license = "MIT"
description = "A board support package for the Electro-Smith Daisy Seed"
repository = "https://github.com/zlosynth/daisy"
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]
keywords = [
    "cortex-m",
    "bsp",
    "stm32h7xx",
    "daisy",
]
readme = "README.md"

[package.metadata.docs.rs]
targets = ["thumbv7em-none-eabihf"]


# - dependencies --------------------------------------------------------------

[dependencies]
cortex-m = "^0.7.4"
cortex-m-rt = { version = "^0.6.13", features = [ "device" ] }
stm32h7xx-hal = { version = "0.12.0", features = [ "stm32h750v", "rt", "revision_v", "usb_hs", "xspi" ] }
cty = "0.2.1" # TODO: Is this needed?
cortex-m-semihosting = "0.3.5"


# - dev dependencies ----------------------------------------------------------

[dev-dependencies]
panic-itm = { version = "~0.4.1" }
panic-halt = "0.2.0"
panic-semihosting = { version = "0.5.6" }


# - features ------------------------------------------------------------------

[features]
log-itm = []


# - profiles ------------------------------------------------------------------

[profile.dev]
debug = true
incremental = false
opt-level = "s" # optimize for binary size

[profile.release]
debug = true
opt-level = "s" #  optimize for binary size


# - examples ------------------------------------------------------------------

[[example]]
name = "blinky"

[[example]]
name = "audio"

[[example]]
name = "adc"

[[example]]
name = "itm"
required-features = [ "log-itm" ]
